[[redirects]]
  from = "https://ohblog.netlify.com/*"
  to = "https://blog.ofo.moe/:splat"
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload


