[[redirects]]
  from = "https://ohblog.netlify.com/*"
  to = "https://blog.ofo.moe/:splat"
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy-Report-Only = "connect-src 'self'; font-src d33wubrfki0l68.cloudfront.net; img-src 'self' data:; manifest-src 'self'; prefetch-src 'self'; script-src-elem 'self' 'unsafe-inline'; worker-src 'self'; script-src 'unsafe-eval'; style-src-attr 'unsafe-inline'; style-src-elem 'unsafe-inline'; report-uri https://ofomoe.report-uri.com/r/d/csp/wizard"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Expect-CT = "max-age=10; enforce; report-uri='https://ofomoe.report-uri.com/r/d/ct/enforce'"
    Report-To = "{"group":"default","max_age":31536000,"endpoints":[{"url":"https://ofomoe.report-uri.com/a/d/g"}],"include_subdomains":true}"
    NEL = "{"report_to":"default","max_age":31536000,"include_subdomains":true}"







